### ISSUE TITLE
Unable to run the file

### ISSUE THREAD

**Issue by saifuddin695** [iammowgoud/NLP-fake-news-detection#8]
Whenever I try executing the "predictionModel.py" file, I get the following error :
Traceback (most recent call last):
  File "predictionModel.py", line 14, in <module>
    pipeline = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

I think there is something wrong with the "pipeline.pkl" file 
Could you please check this error and let me know ASAP ?
Thank You!

**Comment by sangam570** [comment]
Whenever I try executing the "predictionModel.py" file, I get the following error :
Traceback (most recent call last):
File "predictionModel.py", line 14, in
pipeline = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by sangam570** [comment]
> Whenever I try executing the "predictionModel.py" file, I get the following error :
> Traceback (most recent call last):
> File "predictionModel.py", line 14, in
> pipeline = pickle.load(f)
> _pickle.UnpicklingError: invalid load key, 'v'.
> 
> I think there is something wrong with the "pipeline.pkl" file
> Could you please check this error and let me know ASAP ?
> Thank You!

i am also having the same Problem

**Comment by Meetmetha** [comment]
Its because pickle file is on git lfs which is as a pointer in code
Follow Below steps to get whole code:

Fork the repo to one of your users
Go to repo settings
Find "Include Git LFS objects in archives" under the Archives section and check it
Go to the Danger Zone section, select "Archive this repository"
Confirm and authorize.
Return to the archived repository.
Download as .zip
Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.
